from manim import*
class C(Scene):
    def construct(self):
        begin = Text("Интегрирование по частям", color=YELLOW_B, slant=ITALIC, font_size=32)
        self.play(Write(begin))
        self.wait()
        f = Text("Формула выводиться очень легко", color=YELLOW_C, slant=ITALIC, font_size=30)
        text1 = MathTex("\\int{udv} = uv - \\int{vdu}")
        text2 = MathTex("d(uv) = udv + vdu \\Rightarrow")
        box2 = SurroundingRectangle(text2, color=BLUE_B, corner_radius=0.1)
        box2text = Text("Дифференциал от произведение двух функуций",
        color=BLUE_B, slant=ITALIC, font_size=30)
        text3 = MathTex("udv = d(uv) - vdu \\Rightarrow")
        text4 = MathTex("\\int{udv} = \\int{d(uv)} - \\int{vdu} \\Rightarrow")
        text5 = MathTex("\\int{udv} = uv - \\int{vdu}")
        self.play(FadeTransform(begin, text1))
        self.wait()
        box = SurroundingRectangle(text1, corner_radius=0.2)
        self.play(Create(box))
        self.wait()
        self.remove(box)
        self.wait()
        self.play(Write(f.next_to(text1, UP)))
        self.wait(2)
        self.remove(f)
        self.wait(2)
        self.play(FadeTransform(text1, text2))
        self.wait(2)
        self.play(Create(box2))
        self.play(Write(box2text.next_to(box2, UP)))
        self.wait(2)
        self.remove(box2text, box2)
        self.wait()
        self.play(ApplyMethod(text2.shift, LEFT*3))
        self.wait(2)
        self.play(Write(text3.next_to(text2)))
        self.wait(2)
        self.play(Write(text4.next_to(text2, DOWN)))
        self.wait(2)
        self.play(Write(text5.next_to(text3, DOWN).shift(RIGHT*0.5)))
        self.wait(2)
        box1 = SurroundingRectangle(text5, corner_radius=0.1)
        self.play(Create(box1))
        self.wait()
        group = VGroup(box1, text5)
        self.play(ApplyMethod(group.shift, UP*4, LEFT*3.5), run_time=2)
        self.wait()
        g = VGroup(text2, text3, text4)
        self.wait()

        t1 = Text("Рассмотрим пример", color=YELLOW, font_size=30, slant=ITALIC)
        t2 = MathTex("\int{xcos(x)dx}", color=GREEN)
        t3 = MathTex(r" = \int{x}",   r"d(sin(x))", color=GREEN)
        t3_2 = Text("дифференциал от синуса равняется косинусу", color=BLUE_B, font_size=30)
        box3 = SurroundingRectangle(t3[1], color=BLUE_B, corner_radius=0.1).shift(LEFT*0.6)
        t4 = MathTex(" = xsin(x) - \int{sin(x)dx}", color=GREEN)
        t5 = MathTex(" = xsin(x) + cos(x) + C", color=GREEN)
        b1 = Brace(t3[1]).shift(LEFT*0.6)
        btext = b1.get_text("dv")
        b2 = Brace(t3[0], DOWN*0.5).scale(0.3).shift(UP*0.5, LEFT*0.2)
        b2text = b2.get_text("u")
        self.wait()


        self.play(FadeTransform(g, t1))
        self.wait()
        self.play(FadeTransform(t1, t2))
        self.play(ApplyMethod(t2.shift,LEFT*4))
        self.play(Write(t3.next_to(t2, RIGHT)))
        self.wait(2)
        self.play(Create(box3))
        self.play(Write(t3_2.next_to(box3, UP)))
        self.wait(2)
        self.remove(box3, t3_2)
        self.play(Create(b1))
        self.play(Create(btext))
        self.play(Create(b2))
        self.play(Create(b2text))

        self.wait()
        self.play(Write(t4.next_to(t3, RIGHT)))
        self.wait(2)
        self.play(Write(t5.next_to(t4, DOWN)))
        self.wait(2)
        group = VGroup(t2, t3, t4, t5, b1, b2, b2text, btext)
        tex1 = Text("""Иногда этот метод 
                            применяется нескольно раз""", color=YELLOW, slant=ITALIC, font_size=30)
        self.play(FadeTransform(group, tex1))
        self.wait(2)
        tex2 = MathTex(r"\int{x^2sin(x)dx}")
        self.play(FadeTransform(tex1, tex2))
        tex3 = MathTex(" = \int{x^2d(-cos(x))}")
        tex4 = MathTex(" = -x^2cos(x) - \int{-2xcos(x)dx}")
        tex5 = MathTex(" = -x^2cos(x) + \int{2xcos(x)dx}")
        tex6 = MathTex(" = -x^2cos(x) + 2xsin(x) - \int{-2sin(x)dx}")
        tex7 = MathTex(" = -x^2cos(x) + 2xsin(x) + 2cos(x) + C")

        self.play(ApplyMethod(tex2.shift, LEFT*5, UP))
        self.play(Write(tex3.next_to(tex2)))
        self.wait(2)
        self.play(Write(tex4.next_to(tex3)))
        self.wait(2)
        self.play(Write(tex5.next_to(tex3, DOWN)))
        self.wait(2)
        self.play(Write(tex6.next_to(tex5, DOWN)))
        self.wait(2)
        self.play(Write(tex7.next_to(tex6, DOWN)))
        self.wait(3)






